# Generated by Django 6.1.1 on 2026-09-25 19:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('cycle', models.CharField(blank=True, choices=[('Fondamentale', 'Fondamentale'), ('Secondaire', 'Secondaire')], max_length=20)),
                ('annee_scolaire', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['cycle', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(blank=True, choices=[('Directeur(trice)', 'Directeur(trice)'), ('Directeur(trice) Adjoint(e)', 'Directeur(trice) Adjoint(e)'), ('Secrétaire', 'Secrétaire'), ('Comptable', 'Comptable'), ('Caissier(ère)', 'Caissier(ère)'), ('Surveillant(e)', 'Surveillant(e)'), ('Bibliothécaire', 'Bibliothécaire'), ("Agent d'Entretien", "Agent d'Entretien"), ('Gardien', 'Gardien'), ('Infirmier(ère)', 'Infirmier(ère)'), ('Cuisinier(ère)', 'Cuisinier(ère)'), ('Chauffeur', 'Chauffeur'), ('Technicien Informatique', 'Technicien Informatique'), ('Autre', 'Autre')], max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=20)),
                ('nom_parent_tuteur', models.CharField(blank=True, max_length=150)),
                ('telephone_parent', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='core.classe')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_paiement', models.CharField(choices=[("Frais d'Inscription", "Frais d'Inscription"), ('Frais de Scolarité (mensualité)', 'Frais de Scolarité (mensualité)'), ('Réinscription', 'Réinscription'), ("Frais d'Examen", "Frais d'Examen"), ('Uniforme', 'Uniforme'), ('Livres/Matériel', 'Livres/Matériel'), ('Cantine', 'Cantine'), ('Transport', 'Transport'), ('Activités Parascolaires', 'Activités Parascolaires'), ('Autre', 'Autre')], max_length=50)),
                ('methode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Carte Bancaire', 'Carte Bancaire'), ('Virement Bancaire', 'Virement Bancaire'), ('Chèque', 'Chèque'), ('Mobile Money (MonCash/NatCash)', 'Mobile Money (MonCash/NatCash)'), ('Autre', 'Autre')], max_length=50)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Payé', 'Payé'), ('En attente', 'En attente'), ('Partiel', 'Partiel'), ('Annulé', 'Annulé'), ('Remboursé', 'Remboursé')], default='Payé', max_length=50)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.eleve')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('matiere_principale', models.CharField(blank=True, choices=[('ETAP', 'ETAP'), ('Informatique', 'Informatique'), ('Français', 'Français'), ('Créole', 'Créole'), ('Mathématiques', 'Mathématiques'), ('Sciences Expérimentales', 'Sciences Expérimentales'), ('Sciences Sociales', 'Sciences Sociales'), ('Histoire', 'Histoire'), ('Géographie', 'Géographie'), ('Anglais', 'Anglais'), ('Espagnol', 'Espagnol'), ('Éducation Physique et Sportive', 'Éducation Physique et Sportive'), ('Arts Plastiques', 'Arts Plastiques'), ('Musique', 'Musique'), ('Éducation Civique et Morale', 'Éducation Civique et Morale'), ('Philosophie', 'Philosophie'), ('Autre', 'Autre')], max_length=100)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='professeurs', to='core.classe')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(choices=[('ETAP', 'ETAP'), ('Informatique', 'Informatique'), ('Français', 'Français'), ('Créole', 'Créole'), ('Mathématiques', 'Mathématiques'), ('Sciences Expérimentales', 'Sciences Expérimentales'), ('Sciences Sociales', 'Sciences Sociales'), ('Histoire', 'Histoire'), ('Géographie', 'Géographie'), ('Anglais', 'Anglais'), ('Espagnol', 'Espagnol'), ('Éducation Physique et Sportive', 'Éducation Physique et Sportive'), ('Arts Plastiques', 'Arts Plastiques'), ('Musique', 'Musique'), ('Éducation Civique et Morale', 'Éducation Civique et Morale'), ('Philosophie', 'Philosophie'), ('Autre', 'Autre')], max_length=100)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periode', models.CharField(choices=[('1er Trimestre', '1er Trimestre'), ('2e Trimestre', '2e Trimestre'), ('3e Trimestre', '3e Trimestre')], max_length=20)),
                ('annee_scolaire', models.CharField(blank=True, max_length=20)),
                ('date_note', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.eleve')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.professeur')),
            ],
            options={
                'ordering': ['-date_note'],
            },
        ),
    ]
