# Generated by Django 6.1.1 on 2026-09-25 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.AddField(
            model_name="employe",
            name="utilisateur",
            field=models.OneToOneField(
                blank=True,
                help_text="Compte de connexion. Son rôle suit le poste.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="professeur",
            name="utilisateur",
            field=models.OneToOneField(
                blank=True,
                help_text="Compte de connexion du professeur.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professeur",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="doit_changer_mot_de_passe",
            field=models.BooleanField(
                default=False,
                help_text="Coché à la création d'un compte avec un mot de passe provisoire.",
                verbose_name="doit changer son mot de passe",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Peut servir d'identifiant de connexion. Ex : 3712 3456 ou +509 3712 3456.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="classe",
            name="cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Préscolaire", "Préscolaire"),
                    ("Fondamentale", "Fondamentale"),
                    ("Secondaire", "Secondaire"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="poste",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Directeur(trice) en chef", "Directeur(trice) en chef"),
                    (
                        "Directeur(trice) du Kindergarten",
                        "Directeur(trice) du Kindergarten",
                    ),
                    ("Directeur(trice) du primaire", "Directeur(trice) du primaire"),
                    (
                        "Directeur(trice) pédagogique du secondaire",
                        "Directeur(trice) pédagogique du secondaire",
                    ),
                    ("Directeur(trice) Adjoint(e)", "Directeur(trice) Adjoint(e)"),
                    ("Secrétaire", "Secrétaire"),
                    ("Comptable", "Comptable"),
                    ("Caissier(ère)", "Caissier(ère)"),
                    ("Surveillant(e)", "Surveillant(e)"),
                    ("Censeur", "Censeur"),
                    ("Bibliothécaire", "Bibliothécaire"),
                    ("Agent d'Entretien", "Agent d'Entretien"),
                    ("Gardien", "Gardien"),
                    ("Infirmier(ère)", "Infirmier(ère)"),
                    ("Cuisinier(ère)", "Cuisinier(ère)"),
                    ("Chauffeur", "Chauffeur"),
                    ("Technicien Informatique", "Technicien Informatique"),
                    ("Autre", "Autre"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="core.section",
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="À remplir pour une direction de section, un(e) surveillant(e) ou un censeur.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employes",
                to="core.section",
            ),
        ),
        migrations.AddField(
            model_name="professeur",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professeurs",
                to="core.section",
            ),
        ),
    ]
