# Generated by Django 6.1.1 on 2026-09-26 00:13

import core.choices
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sections_et_roles_de_depart"),
    ]

    operations = [
        migrations.AddField(
            model_name="professeur",
            name="adresse",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="professeur",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professeur",
            name="diplome",
            field=models.CharField(blank=True, max_length=150, verbose_name="diplôme"),
        ),
        migrations.AlterField(
            model_name="professeur",
            name="date_embauche",
            field=models.DateField(
                blank=True, null=True, verbose_name="début à l'école"
            ),
        ),
        migrations.CreateModel(
            name="Creneau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex : 1re heure, Récréation", max_length=50
                    ),
                ),
                ("heure_debut", models.TimeField(verbose_name="début")),
                ("heure_fin", models.TimeField(verbose_name="fin")),
                (
                    "est_un_cours",
                    models.BooleanField(
                        default=True,
                        help_text="Décoché pour une récréation.",
                        verbose_name="heure de cours",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creneaux",
                        to="core.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "créneau",
                "ordering": ["section", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matiere",
                    models.CharField(
                        choices=[
                            ("ETAP", "ETAP"),
                            ("Informatique", "Informatique"),
                            ("Français", "Français"),
                            ("Créole", "Créole"),
                            ("Mathématiques", "Mathématiques"),
                            ("Sciences Expérimentales", "Sciences Expérimentales"),
                            ("Sciences Sociales", "Sciences Sociales"),
                            ("Histoire", "Histoire"),
                            ("Géographie", "Géographie"),
                            ("Anglais", "Anglais"),
                            ("Espagnol", "Espagnol"),
                            (
                                "Éducation Physique et Sportive",
                                "Éducation Physique et Sportive",
                            ),
                            ("Arts Plastiques", "Arts Plastiques"),
                            ("Musique", "Musique"),
                            (
                                "Éducation Civique et Morale",
                                "Éducation Civique et Morale",
                            ),
                            ("Philosophie", "Philosophie"),
                            ("Autre", "Autre"),
                        ],
                        max_length=100,
                        verbose_name="matière",
                    ),
                ),
                (
                    "jour",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Lundi"),
                            (2, "Mardi"),
                            (3, "Mercredi"),
                            (4, "Jeudi"),
                            (5, "Vendredi"),
                        ]
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Proposé", "Proposé"), ("Validé", "Validé")],
                        default="Proposé",
                        max_length=20,
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(
                        default=core.choices.annee_scolaire_courante, max_length=20
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours",
                        to="core.classe",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours",
                        to="core.professeur",
                    ),
                ),
                (
                    "creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cours",
                        to="core.creneau",
                        verbose_name="heure",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cours",
                "ordering": ["jour", "creneau__heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Titulaire", "Titulaire"),
                            ("Deuxième maîtresse", "Deuxième maîtresse"),
                        ],
                        default="Titulaire",
                        max_length=30,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Vide tant que le professeur est dans la classe.",
                        null=True,
                        verbose_name="fin",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="core.classe",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="core.professeur",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_debut"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("date_fin__isnull", True)),
                        fields=("classe", "role"),
                        name="affectation_un_role_par_classe",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("date_fin__isnull", True)),
                        fields=("professeur",),
                        name="affectation_une_classe_par_professeur",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="creneau",
            constraint=models.UniqueConstraint(
                fields=("section", "heure_debut"), name="creneau_unique_par_section"
            ),
        ),
        migrations.AddConstraint(
            model_name="cours",
            constraint=models.UniqueConstraint(
                fields=("classe", "jour", "creneau", "annee_scolaire"),
                name="cours_une_classe_un_creneau",
            ),
        ),
        migrations.AddConstraint(
            model_name="cours",
            constraint=models.UniqueConstraint(
                fields=("professeur", "jour", "creneau", "annee_scolaire"),
                name="cours_un_professeur_un_creneau",
            ),
        ),
    ]
