# Generated by Django 6.1.1 on 2026-09-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_horaires_secondaire_par_defaut"),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="adresse",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="date_naissance",
            field=models.DateField(
                blank=True, null=True, verbose_name="date de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="date_embauche",
            field=models.DateField(
                blank=True,
                help_text="Premier jour à l'école.",
                null=True,
                verbose_name="date d'embauche",
            ),
        ),
        migrations.AlterField(
            model_name="professeur",
            name="date_embauche",
            field=models.DateField(
                blank=True,
                help_text="Premier jour à l'école.",
                null=True,
                verbose_name="date d'embauche",
            ),
        ),
    ]
