# Generated by Django 6.1.1 on 2026-09-26 22:55

import core.photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_employes_naissance_embauche"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo d'identité, 5 Mo au plus.",
                upload_to=core.photos.chemin_photo,
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo d'identité, 5 Mo au plus.",
                upload_to=core.photos.chemin_photo,
            ),
        ),
        migrations.AddField(
            model_name="professeur",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo d'identité, 5 Mo au plus.",
                upload_to=core.photos.chemin_photo,
            ),
        ),
    ]
