# Generated by Django 6.1.1 on 2026-09-26 23:09

import core.photos
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("message", models.TextField()),
                (
                    "recu_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="reçu le"),
                ),
                ("traite", models.BooleanField(default=False, verbose_name="traité")),
                ("traite_le", models.DateTimeField(blank=True, null=True)),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "message du site",
                "verbose_name_plural": "messages du site",
                "ordering": ["traite", "-recu_le"],
            },
        ),
        migrations.CreateModel(
            name="Preinscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo d'identité, 5 Mo au plus.",
                        upload_to=core.photos.chemin_photo,
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="numéro de dossier",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                ("date_naissance", models.DateField(verbose_name="date de naissance")),
                (
                    "genre",
                    models.CharField(
                        choices=[("Masculin", "Masculin"), ("Féminin", "Féminin")],
                        max_length=20,
                    ),
                ),
                (
                    "ecole_precedente",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="école précédente"
                    ),
                ),
                (
                    "nom_parent",
                    models.CharField(
                        max_length=150, verbose_name="nom du parent ou tuteur"
                    ),
                ),
                (
                    "telephone_parent",
                    models.CharField(max_length=30, verbose_name="téléphone"),
                ),
                (
                    "email_parent",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=250)),
                (
                    "acte_naissance",
                    models.FileField(
                        blank=True,
                        upload_to=core.photos.chemin_piece,
                        verbose_name="acte de naissance",
                    ),
                ),
                (
                    "dernier_bulletin",
                    models.FileField(
                        blank=True,
                        upload_to=core.photos.chemin_piece,
                        verbose_name="dernier bulletin",
                    ),
                ),
                (
                    "etape",
                    models.CharField(
                        choices=[
                            ("Reçue", "Reçue"),
                            ("Chez la direction", "Chez la direction"),
                            ("Acceptée", "Acceptée"),
                            ("Refusée", "Refusée"),
                            ("Inscrite", "Inscrite"),
                        ],
                        default="Reçue",
                        max_length=30,
                        verbose_name="étape",
                    ),
                ),
                (
                    "rendez_vous",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rendez-vous avec la famille au secrétariat.",
                        null=True,
                        verbose_name="rendez-vous",
                    ),
                ),
                (
                    "note_interne",
                    models.TextField(
                        blank=True,
                        help_text="Visible seulement par le personnel.",
                        verbose_name="note du secrétariat",
                    ),
                ),
                (
                    "avis_direction",
                    models.TextField(blank=True, verbose_name="avis de la direction"),
                ),
                ("decision_le", models.DateTimeField(blank=True, null=True)),
                (
                    "date_demande",
                    models.DateTimeField(auto_now_add=True, verbose_name="reçue le"),
                ),
                ("mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "classe_demandee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preinscriptions",
                        to="core.classe",
                        verbose_name="classe demandée",
                    ),
                ),
                (
                    "decision_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preinscription",
                        to="core.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "préinscription",
                "ordering": ["-date_demande"],
            },
        ),
    ]
