# Generated by Django 6.1.1 on 2026-09-27 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_preinscriptions_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom complet")),
                (
                    "telephone",
                    models.CharField(max_length=30, verbose_name="téléphone"),
                ),
                (
                    "telephone_normalise",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=250)),
                (
                    "code_acces",
                    models.CharField(
                        blank=True,
                        help_text="Remis par le secrétariat ; il ne sert qu'une fois.",
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="code d'accès",
                    ),
                ),
                ("code_cree_le", models.DateTimeField(blank=True, null=True)),
                (
                    "compte_cree_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="compte créé le"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "enfants",
                    models.ManyToManyField(
                        blank=True, related_name="parents", to="core.eleve"
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        blank=True,
                        help_text="Compte créé par le parent avec son code d'accès.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
    ]
