# Generated by Django 6.1.1 on 2026-09-27 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_parents"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="annonces_vues_le",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="espace_vu_le",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("texte", models.TextField()),
                (
                    "publiee_le",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="publiée le"
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annonces",
                        to="core.classe",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annonces",
                        to="core.section",
                    ),
                ),
            ],
            options={
                "ordering": ["-publiee_le"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("description", models.TextField(verbose_name="ce qui s'est passé")),
                (
                    "sanction",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="sanction ou suite donnée",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Signalé", "Signalé"),
                            ("En cours", "En cours"),
                            ("Clos", "Clos"),
                        ],
                        default="Signalé",
                        max_length=20,
                    ),
                ),
                (
                    "convocation_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="parents convoqués le"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="core.eleve",
                    ),
                ),
                (
                    "signale_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "type",
                    models.CharField(
                        choices=[("Absence", "Absence"), ("Retard", "Retard")],
                        default="Absence",
                        max_length=10,
                    ),
                ),
                (
                    "minutes_retard",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="minutes de retard"
                    ),
                ),
                (
                    "justifiee",
                    models.BooleanField(default=False, verbose_name="justifiée"),
                ),
                ("motif", models.CharField(blank=True, max_length=200)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="core.eleve",
                    ),
                ),
                (
                    "signalee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "eleve__nom", "eleve__prenom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("eleve", "date"),
                        name="une_absence_par_eleve_et_par_jour",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Appel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("fait_le", models.DateTimeField(auto_now=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appels",
                        to="core.classe",
                    ),
                ),
                (
                    "fait_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("classe", "date"),
                        name="un_appel_par_classe_et_par_jour",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee_scolaire", models.CharField(max_length=20)),
                (
                    "periode",
                    models.CharField(
                        choices=[
                            ("1er Trimestre", "1er Trimestre"),
                            ("2e Trimestre", "2e Trimestre"),
                            ("3e Trimestre", "3e Trimestre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lignes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Notes de chaque matière au moment de la validation.",
                    ),
                ),
                (
                    "moyenne",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rang", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("effectif", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("absences", models.PositiveSmallIntegerField(default=0)),
                ("retards", models.PositiveSmallIntegerField(default=0)),
                (
                    "conduite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Excellente", "Excellente"),
                            ("Très bonne", "Très bonne"),
                            ("Bonne", "Bonne"),
                            ("Passable", "Passable"),
                            ("À améliorer", "À améliorer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "appreciation",
                    models.TextField(blank=True, verbose_name="appréciation"),
                ),
                ("valide", models.BooleanField(default=False, verbose_name="validé")),
                (
                    "valide_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="validé le"
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulletins",
                        to="core.classe",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletins",
                        to="core.eleve",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-annee_scolaire", "periode", "eleve__nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("eleve", "annee_scolaire", "periode"),
                        name="un_bulletin_par_eleve_et_par_trimestre",
                    )
                ],
            },
        ),
    ]
