# Generated by Django 6.1.1 on 2026-09-27 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def informer_les_incidents_deja_traites(apps, schema_editor):
    """Avant, les parents voyaient un incident dès qu'il était traité : on garde ce qu'ils voyaient."""
    apps.get_model("core", "Incident").objects.exclude(statut="Signalé").update(informer_parents=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_vie_scolaire_bulletins_annonces"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="annonces_vues_le",
        ),
        migrations.RemoveField(
            model_name="parent",
            name="espace_vu_le",
        ),
        migrations.AddField(
            model_name="incident",
            name="informer_parents",
            field=models.BooleanField(
                default=False,
                help_text="Les parents voient l'incident et la suite donnée dans leur espace, et reçoivent une notification.",
                verbose_name="informer les parents",
            ),
        ),
        migrations.CreateModel(
            name="AlerteSante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="ce qu'il ou elle a")),
                (
                    "mesure",
                    models.CharField(
                        choices=[
                            ("Se repose à l'école", "Se repose à l'école"),
                            (
                                "Un parent doit venir à l'école",
                                "Un parent doit venir à l'école",
                            ),
                            (
                                "Conduit(e) chez le médecin",
                                "Conduit(e) chez le médecin",
                            ),
                        ],
                        default="Se repose à l'école",
                        max_length=60,
                        verbose_name="ce que fait l'école",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes_sante",
                        to="core.eleve",
                        verbose_name="élève",
                    ),
                ),
                (
                    "signale_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "élève malade",
                "verbose_name_plural": "élèves malades",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("Absence", "Absence"),
                            ("Retard", "Retard"),
                            ("Comportement", "Comportement"),
                            ("Convocation", "Convocation"),
                            ("Santé", "Santé"),
                            ("Bulletin", "Bulletin"),
                            ("Annonce", "Annonce"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("texte", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("lue_le", models.DateTimeField(blank=True, null=True)),
                (
                    "absence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.absence",
                    ),
                ),
                (
                    "alerte_sante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.alertesante",
                    ),
                ),
                (
                    "annonce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.annonce",
                    ),
                ),
                (
                    "bulletin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.bulletin",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.eleve",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.incident",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.parent",
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["parent", "lue_le"],
                        name="core_notifi_parent__6e51cc_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(informer_les_incidents_deja_traites, migrations.RunPython.noop),
    ]
