# Generated by Django 6.1.1 on 2026-09-27 19:34

import core.photos
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_notifications_sante_informer_parents"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("Génies en herbe", "Génies en herbe"),
                            ("Concours", "Concours"),
                            ("Sortie", "Sortie"),
                            ("Fête", "Fête"),
                            ("Sport", "Sport"),
                            ("Autre", "Autre"),
                        ],
                        default="Génies en herbe",
                        max_length=30,
                        verbose_name="type d'activité",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "texte",
                    models.TextField(
                        blank=True,
                        help_text="Par exemple : les classes en compétition, les gagnants, un mot de la direction.",
                        verbose_name="ce qui s'est passé",
                    ),
                ),
                (
                    "publiee",
                    models.BooleanField(
                        default=True, verbose_name="visible sur le site de l'école"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "activité",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PhotoActivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=core.photos.chemin_activite)),
                ("vignette", models.ImageField(upload_to=core.photos.chemin_vignette)),
                ("ajoutee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.activite",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo d'activité",
                "ordering": ["ajoutee_le", "pk"],
            },
        ),
    ]
