"""
Django settings for gestion_ecole project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ─────────────────────────────────────────────────────────────
# Réglages lus dans l'environnement (jamais de secret dans le code).
# En développement, copiez .env.example en .env ; en production,
# définissez les mêmes variables chez l'hébergeur.
# ─────────────────────────────────────────────────────────────
def _charger_fichier_env(chemin):
    """Charge les lignes CLE=valeur d'un fichier .env sans écraser l'environnement."""
    if not chemin.exists():
        return
    for ligne in chemin.read_text(encoding="utf-8").splitlines():
        ligne = ligne.strip()
        if not ligne or ligne.startswith("#") or "=" not in ligne:
            continue
        cle, valeur = ligne.split("=", 1)
        os.environ.setdefault(cle.strip(), valeur.strip().strip("\"'"))


def _env_bool(nom, defaut=False):
    return (os.environ.get(nom) or ("1" if defaut else "0")).strip().lower() in ("1", "true", "oui", "yes")


def _env_liste(nom, defaut=""):
    return [v.strip() for v in (os.environ.get(nom) or defaut).split(",") if v.strip()]


_charger_fichier_env(BASE_DIR / ".env")

DEBUG = _env_bool("DJANGO_DEBUG")

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY n'est pas défini. En développement, copiez .env.example en .env ; "
            "en production, définissez DJANGO_SECRET_KEY chez l'hébergeur."
        )
    SECRET_KEY = "dev-seulement-cle-a-ne-jamais-utiliser-en-production"

ALLOWED_HOSTS = _env_liste("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1" if DEBUG else "")
CSRF_TRUSTED_ORIGINS = _env_liste("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'site_public',
]

AUTH_USER_MODEL = 'core.Utilisateur'

# Connexion avec le nom d'utilisateur, l'e-mail ou le téléphone
AUTHENTICATION_BACKENDS = ['core.backends.IdentifiantBackend']

LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:espace'
LOGOUT_REDIRECT_URL = 'core:login'

# Session fermée après 30 minutes sans activité
SESSION_COOKIE_AGE = 30 * 60
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.ChangementMotDePasseMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_ecole.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.acces',
                'site_public.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_ecole.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# DB_ENGINE=sqlite (par défaut, rien à installer) pour le développement,
# DB_ENGINE=postgresql (conseillé) ou mysql en production, avec DB_NAME,
# DB_USER, DB_PASSWORD, DB_HOST et DB_PORT.

_MOTEURS = {
    "sqlite": "django.db.backends.sqlite3",
    "postgresql": "django.db.backends.postgresql",
    "mysql": "django.db.backends.mysql",
}
_moteur = (os.environ.get("DB_ENGINE") or "sqlite").strip().lower()
if _moteur not in _MOTEURS:
    raise ImproperlyConfigured(f"DB_ENGINE doit valoir sqlite, postgresql ou mysql (reçu : {_moteur}).")

if _moteur == "sqlite":
    DATABASES = {
        'default': {
            'ENGINE': _MOTEURS["sqlite"],
            'NAME': BASE_DIR / (os.environ.get("DB_NAME") or "db.sqlite3"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _MOTEURS[_moteur],
            'NAME': os.environ.get("DB_NAME") or "gestion_ecole",
            'USER': os.environ.get("DB_USER", ""),
            'PASSWORD': os.environ.get("DB_PASSWORD", ""),
            'HOST': os.environ.get("DB_HOST") or "localhost",
            'PORT': os.environ.get("DB_PORT", ""),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'America/Port-au-Prince'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Photos et pièces jointes. Elles ne sont jamais servies directement : une vue
# vérifie les droits avant d'envoyer une photo (voir core/photos.py).
MEDIA_ROOT = Path(os.environ.get("DJANGO_MEDIA_ROOT") or BASE_DIR / "media")
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
